### ISSUE TITLE
Lasercount not working 

### ISSUE THREAD

**Issue by cyan** [starfi5h/LaserClearing#2]
Hi
i ve changed the value for MaxCount in the laser category (tried 6 and 8) and even after restarting the game (even the computer itself as i tried those changes few days ago) and there is still only 3 laser capturing stuff around.

**Comment by starfi5h** [comment]
You'll need to lower `CheckIntervalTick` too. It can be viewed as laser cool-down time.

**Comment by cyan** [comment]
oh great thanks it work fine indeed now xD
