### ISSUE TITLE
LaserClearing v1.0.6 by starfi5h建议

### ISSUE THREAD

**Issue by A-nuo666** [starfi5h/LaserClearing#5]
作者大佬你好，你这个激光采资源的mod超级棒，我超级喜欢。由于我比较懒所以想提点建议：这个mod前期在使用的过程很方便，如果能加上靠近矿自动激光采矿那就更加完美了，游戏本身可以自行通过机甲挖矿，但是这个挖矿很慢也是单线的，如果激光可以挖矿，那么在前期可以让游戏进行的更加的舒服，激光是消耗能量的所以最好可以加快采矿的速度，目前就想到这一些作者大佬看下是否有用。

**Comment by starfi5h** [comment]
这个.. 比较麻烦。目前的代码都是针对树木石头为主的，在开采完成后会破坏目标。
而且机甲只有在非常前期才会手动挖矿，中后期都是铺矿机自动化了。如果加入挖矿的功能很容易爆仓(机甲背包)，不好控制

想增加机甲采矿速度建议直接用[Multfunction mod](https://thunderstore.io/c/dyson-sphere-program/p/blacksnipebiu/Multfuntion_mod/)修改人物能力

**Comment by A-nuo666** [comment]
好的，谢谢大佬的回复，这个mod是有用的，有其他问题了再给你反馈哈
